version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE:      documents_api
      MYSQL_USER:          user
      MYSQL_PASSWORD:      password
      TZ:                  Asia/Tokyo   
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 33306:3306
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
