CREATE SCHEMA IF NOT EXISTS `documents_api` DEFAULT CHARACTER SET utf8;
USE `documents_api`;

CREATE TABLE IF NOT EXISTS `documents_api`.`users` (
  `id`         BIGINT(20)   UNSIGNED NOT NULL AUTO_INCREMENT,
  `username`   VARCHAR(255) NOT NULL UNIQUE,
  `updated_at` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `documents_api`.`user_auths` (
  `user_id`         BIGINT(20)   UNSIGNED NOT NULL,
  `email`           VARCHAR(255) NOT NULL UNIQUE,
  `hash`            VARCHAR(255) NOT NULL,
  `updated_at`      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `documents_api`.`user_details` (
  `user_id`         BIGINT(20)   UNSIGNED NOT NULL,
  `nickname`        VARCHAR(255) NOT NULL,
  `updated_at`      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `documents_api`.`auth_tokens` (
  `id`            BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id`       BIGINT(20) UNSIGNED NOT NULL,
  `token`         VARCHAR(255)        NOT NULL,
  `expiry`        TIMESTAMP           NOT NULL,
  `updated_at`    TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at`    TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE=InnoDB;
